### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by svensis** [C0nw0nk/Garrys-Mod-Anti-Cheat#2]
[ERROR] addons/anticheat/lua/autorun/server/anti-recoil.lua:39: attempt to call method 'Clip1' (a nil value)
1. fn - addons/anticheat/lua/autorun/server/anti-recoil.lua:39
   1. unknown - addons/ulib/lua/ulib/shared/hook.lua:105

plz help, i think its with ulx and anticheat im running ttt

**Comment by C0nw0nk** [comment]
Updated the script should solve the problem for you https://github.com/C0nw0nk/Garrys-Mod-Anti-Cheat/commit/8993e3930d30a9e372873b5d40cb5dffd8243a69
